### ISSUE TITLE
error when opening Umemaro3D releases

### ISSUE THREAD

**Issue by CuddleBear92** [CTFAK/CTFAK#1]
Hey i just tried CTFAK today on some clickteam Umemaro3D releases. 
All 4 of those i have (5 available) have all the same error and fail to extract anything.

Error popup:

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at CTFAK.GUI.MainForm.InitImages() in E:\DotNetCTF\CTFAK\GUI\MainForm.cs:line 588
   at CTFAK.GUI.MainForm.AfterLoad() in E:\DotNetCTF\CTFAK\GUI\MainForm.cs:line 294
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
```

Full log:
```
[22: 8:41:304] DecryptionLibExist: True
[22: 8:41:357] Executable: imadoki_eng

[22: 8:41:359] EXE Header: MZ
[22: 8:41:360] PE Header: PE
[22: 8:41:362] First Short: 7777
[22: 8:41:363] Found PackData header!
Reading PackData header.
[22: 8:41:365] Found 53 Pack Files
[22: 8:41:651] 
Packdata Done

[22: 8:41:675] Combined data Cheeky GirlUmemaro3DC:\Users\Hiroyuki\Desktop\作業用\いまどき\いまどき.mfa
[22: 8:41:682] First 16-Bytes of key: 43 68 65 65 6B 79 20 47 69 72 6C 55 6D 65 6D 61 
[22: 8:41:684] 桃敥祫䜠物啬敭慭潲䐳㩃啜敳獲䡜物祯歵屩敄歳潴屰㼿尿㼿㼿㽜㼿⸿晭a [22: 8:41:695] ERROR: 
[22: 8:41:704] Joveler.Compression.ZLib.ZLibException: [DataError] incorrect header check
   at Joveler.Compression.ZLib.ZLibException.CheckReturnValue(ZLibRet ret, ZStreamL32 zs)
[22: 8:41:710] Loading GUI
[22: 8:41:719] ERROR: 
[22: 8:41:721] System.NullReferenceException: Object reference not set to an instance of an object.
   at CTFAK.GUI.MainForm.InitImages() in E:\DotNetCTF\CTFAK\GUI\MainForm.cs:line 588
[22: 8:41:722] ERROR: 
[22: 8:41:726] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at CTFAK.GUI.MainForm.InitImages() in E:\DotNetCTF\CTFAK\GUI\MainForm.cs:line 588
   at CTFAK.GUI.MainForm.AfterLoad() in E:\DotNetCTF\CTFAK\GUI\MainForm.cs:line 294
   at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   ```
   
   Tested this on the following DLSite products (NFSW):
   RE303567 - Cheeky Girl
   RE303569 - Horny Girl
   RE303571 - Sexy trainer Shoko Sugimoto
   RE303573 - Sisters' Sexual Circumstances
   
   You might find these tiles else where like nyaa
   
   EDIT: note Source Explorer is extracting textures correctly with these titles.
   
   Please Ping me on Discord if you need anything of me to test.

**Comment by CONIGUERO** [comment]
> Hey i just tried CTFAK today on some clickteam Umemaro3D releases.
> All 4 of those i have (5 available) have all the same error and fail to extract anything.
> 
> Error popup:
> 
> ```
> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at CTFAK.GUI.MainForm.InitImages() in E:\DotNetCTF\CTFAK\GUI\MainForm.cs:line 588
>    at CTFAK.GUI.MainForm.AfterLoad() in E:\DotNetCTF\CTFAK\GUI\MainForm.cs:line 294
>    at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
> ```
> 
> Full log:
> 
> ```
> [22: 8:41:304] DecryptionLibExist: True
> [22: 8:41:357] Executable: imadoki_eng
> 
> [22: 8:41:359] EXE Header: MZ
> [22: 8:41:360] PE Header: PE
> [22: 8:41:362] First Short: 7777
> [22: 8:41:363] Found PackData header!
> Reading PackData header.
> [22: 8:41:365] Found 53 Pack Files
> [22: 8:41:651] 
> Packdata Done
> 
> [22: 8:41:675] Combined data Cheeky GirlUmemaro3DC:\Users\Hiroyuki\Desktop\作業用\いまどき\いまどき.mfa
> [22: 8:41:682] First 16-Bytes of key: 43 68 65 65 6B 79 20 47 69 72 6C 55 6D 65 6D 61 
> [22: 8:41:684] 桃敥祫䜠物啬敭慭潲䐳㩃啜敳獲䡜物祯歵屩敄歳潴屰㼿尿㼿㼿㽜㼿⸿晭a [22: 8:41:695] ERROR: 
> [22: 8:41:704] Joveler.Compression.ZLib.ZLibException: [DataError] incorrect header check
>    at Joveler.Compression.ZLib.ZLibException.CheckReturnValue(ZLibRet ret, ZStreamL32 zs)
> [22: 8:41:710] Loading GUI
> [22: 8:41:719] ERROR: 
> [22: 8:41:721] System.NullReferenceException: Object reference not set to an instance of an object.
>    at CTFAK.GUI.MainForm.InitImages() in E:\DotNetCTF\CTFAK\GUI\MainForm.cs:line 588
> [22: 8:41:722] ERROR: 
> [22: 8:41:726] System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.NullReferenceException: Object reference not set to an instance of an object.
>    at CTFAK.GUI.MainForm.InitImages() in E:\DotNetCTF\CTFAK\GUI\MainForm.cs:line 588
>    at CTFAK.GUI.MainForm.AfterLoad() in E:\DotNetCTF\CTFAK\GUI\MainForm.cs:line 294
>    at System.ComponentModel.BackgroundWorker.OnRunWorkerCompleted(RunWorkerCompletedEventArgs e)
>    --- End of inner exception stack trace ---
>    at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
>    at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
> ```
> 
> Tested this on the following DLSite products (NFSW):
> RE303567 - Cheeky Girl
> RE303569 - Horny Girl
> RE303571 - Sexy trainer Shoko Sugimoto
> RE303573 - Sisters' Sexual Circumstances
> 
> You might find these tiles else where like nyaa
> 
> EDIT: note Source Explorer is extracting textures correctly with these titles.
> 
> Please Ping me on Discord if you need anything of me to test.

It's because the game was made with 2.5+
We don't support that ATM, however we will in a future release.
